### ISSUE TITLE
Delete obsolete versions and snapshot

### ISSUE THREAD

**Issue by longstone** [geoffreywiseman/mvnclean#11]
Enhance the mvnclean-tool to also delete obsolete folders. 
As example, only the "3.1.19" Version should remain.

```
C:\Users\longstone\.m2\repository\com\example\artifact\artifact-id>ls -lsa
total 60
 16 drwxr-xr-x 1 longstone 1049089    0 Apr 20 13:00 .
 4 drwxr-xr-x 1 longstone 1049089    0 Sep  5  2014 ..
 4 drwxr-xr-x 1 longstone 1049089    0 Jul 24  2014 3.0.2-SNAPSHOT
 0 drwxr-xr-x 1 longstone 1049089    0 Jul 24  2014 3.0.4
 4 drwxr-xr-x 1 longstone 1049089    0 Jan 29 11:32 3.1.13
 4 drwxr-xr-x 1 longstone 1049089    0 Jan 29 11:34 3.1.18
 0 drwxr-xr-x 1 longstone 1049089    0 Feb  3 15:40 3.1.19
 4 drwxr-xr-x 1 longstone 1049089    0 Feb  3 15:50 3.1.19-SNAPSHOT
 4 drwxr-xr-x 1 longstone 1049089    0 Feb  8 11:27 3.1.20-SNAPSHOT
 4 drwxr-xr-x 1 longstone 1049089    0 Aug 11  2014 3.1.5
 4 drwxr-xr-x 1 longstone 1049089    0 Jul 24  2014 SNAPSHOT
 ...
```

May be via a flag?

**Comment by geoffreywiseman** [comment]
@longstone:
Hm, interesting. Are these empty folders the result of running `mvnclean`? When I run `mvnclean` locally, the folders go away along with their content, so I'm just wondering if there's some kind of defect in a particular (e.g. Windows) environment?

Or do these empty folders pre-date `mvnclean`, and you'd just like `mvnclean` to handle them as well?

**Comment by geoffreywiseman** [comment]
I originally misread this issue -- you're not talking about empty folders, you're talking about removing versions that are older than the latest, as well as the SNAPSHOT.

My main problem with this approach, which is why I went with last-accessed date instead, is you might be using versions other than 'the current', and this could end up removing dependencies you're using. For instance, if I'm working on multiple projects, it's entirely possible that one project uses the same dependency as another project, but not the same version. 

For my own use, I want to remove the dependencies that I don't seem to be using currently, and the last-accessed date seems to address that better. Your use may well be different, and I could imagine handling this with a flag, as you suggested. You're not worried about deleting dependencies you're using? Or you never have dependencies where multiple versions or older versions are the ones in use?

If anyone else really wants to use `mvnclean` this way, let me know -- would be useful to understand how popular this approach would be.

**Comment by longstone** [comment]
Well my intention was to delete all, beside to the last version. My thought was, that a older dependency would be downloaded as well. But after reading your answer I'm totally on your side. Thanks for this clearification and this helpful tool.

**Comment by geoffreywiseman** [comment]
On the upside, because I misread your initial request, I ended up discovering the my repo had a lot of empty folders and ended up adding pruning for empty folders to the tool, so thanks for that. ;)
